services:
  # Production override for the web app (SSG, no HMR)
  web:
    image: stack-bun-node:latest
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    environment:
      AUTH_TRUST_HOST: "true"
      # Lock server to 5174 so healthcheck/Traefik match
      PORT: "5174"
      HOST: "0.0.0.0"
      # Disable live-reload in prod runner to allow bfcache (no WebSocket/SSE)
      LIVE_RELOAD: "0"
      LIVE_RELOAD_SSE: "0"
      # Provide a stable origin for Qwik SSG (LAN HTTPS via Traefik)
      SITE_ORIGIN: "https://${PUBLIC_IP:-127.0.0.1}:5173"
    # Expose static server directly when running without Traefik
    ports:
      - "5174:5174"
    healthcheck:
      # Use Bun to probe the local HTTP server (Node is not installed in oven/bun)
      test: ["CMD-SHELL", "bun -e \"try{const r=await fetch('http://127.0.0.1:5174/index.html');process.exit(r.status<500?0:1)}catch(e){process.exit(1)}\" "]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 60s
    labels:
      - "traefik.enable=true"
      # Same routing as dev: Traefik fronts the app on 5173
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.middlewares=web-compress@docker,security_headers@file,web-headers@docker,web-cache-html@docker"
      - "traefik.http.middlewares.web-headers.headers.customResponseHeaders.Alt-Svc=h3=\":5173\"; ma=86400"
      - "traefik.http.middlewares.web-headers.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.web-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.web-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.web-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.web-compress.compress=true"
      - "traefik.http.middlewares.web-cache-html.headers.customResponseHeaders.Cache-Control=public, max-age=600, stale-while-revalidate=86400"
      - "traefik.http.middlewares.web-cache-html.headers.customResponseHeaders.Vary=Accept-Encoding"
      - "traefik.http.routers.web.priority=10"
      - "traefik.http.services.web.loadbalancer.server.port=5174"
      # Asset router for long-cache and compression
      - "traefik.http.routers.web-assets.rule=PathPrefix(`/assets`) || PathPrefix(`/build`) || Path(`/theme-init.js`)"
      - "traefik.http.routers.web-assets.entrypoints=websecure"
      - "traefik.http.routers.web-assets.tls=true"
      - "traefik.http.routers.web-assets.priority=100"
      - "traefik.http.routers.web-assets.service=web"
      - "traefik.http.routers.web-assets.middlewares=web-compress@docker,web-cache-asset@docker"
      - "traefik.http.middlewares.web-cache-asset.headers.customResponseHeaders.Cache-Control=public, max-age=31536000, immutable"
      - "traefik.http.middlewares.web-cache-asset.headers.customResponseHeaders.Vary=Accept-Encoding"

  # Rust Gateway (prod mode — same binary run as dev for now)
  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    environment:
      # Quieter logs by default; override by setting RUST_LOG in your shell
      RUST_LOG: ${RUST_LOG:-warn,tower_http=info}
      ADMIN_EMAIL: "${ADMIN_EMAIL:-admin@example.com}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin12345}"
      # Allow HTTPS origins on 5173 (LAN IP via Traefik)
      CORS_ALLOW_ORIGINS: "https://localhost:5173,https://127.0.0.1:5173,https://${PUBLIC_IP:-127.0.0.1}:5173"
      CORS_ALLOW_ANY_IP_PORTS: "5173"
      GATEWAY_ADDR: 0.0.0.0:7000
    # Mount admin seed file for initial admin creation
    volumes:
      - ./apps/gateway/admin.seed:/config/admin.seed:ro
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash -lc 'exec 3<>/dev/tcp/127.0.0.1/7000 && echo -e \"GET /healthz HTTP/1.0\\r\\n\\r\\n\" >&3 && grep -q ok <&3' "]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls=true"
      - "traefik.http.routers.gateway.priority=200"
      - "traefik.http.services.gateway.loadbalancer.server.port=7000"

  traefik:
    image: traefik:v3.5.2
    command:
      - "--entrypoints.websecure.address=:5173"
      - "--entrypoints.websecure.http3=true"
      - "--ping=true"
      - "--ping.entrypoint=websecure"
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
    ports:
      - "5173:5173/tcp"
      - "5173:5173/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./apps/web/certs:/certs:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    depends_on:
      web:
        condition: service_healthy
      gateway:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-host.rule=HostRegexp(`traefik\\..+`)"
      - "traefik.http.routers.traefik-host.entrypoints=websecure"
      - "traefik.http.routers.traefik-host.tls=true"
      - "traefik.http.routers.traefik-host.service=api@internal"

  announce:
    image: alpine:3
    environment:
      PUBLIC_IP: ${PUBLIC_IP:-127.0.0.1}
    command:
      - sh
      - -c
      - |
        echo "";
        echo "Traefik ready. Open:";
        echo "  - Web (prod preview): https://localhost:5173  (or https://$${PUBLIC_IP}:5173)";
        echo "  - Dashboard:          https://traefik.$${PUBLIC_IP}:5173";
        echo "";
        while true; do sleep 3600; done
    depends_on:
      web:
        condition: service_healthy
      gateway:
        condition: service_healthy
      traefik:
        condition: service_started

volumes:
  cargo-registry:
  cargo-git:
  cargo-target:
